// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: manifest.proto

package manifestpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Manifest mirrors data.Manifest (internal/data/manifest.go). New fields must
// keep wire compatibility — append-only field numbers, no renumbering.
//
// Field-number ledger:
//
//	1..5   Class / Size / ChunkSize / ETag / Chunks
//	6      PartChunkCounts (US-049 multipart SSE; pre-US-001 label
//	       part_chunks; wire format unchanged)
//	7      PartChecksums (US-049 multipart SSE)
//	8      BackendRef (US-008 S3-over-S3 data backend)
//	12     SSEInfo (US-013 SSE mode wire record)
//	13     PartChunks (US-001 per-part byte ranges)
type Manifest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Class           string                 `protobuf:"bytes,1,opt,name=class,proto3" json:"class,omitempty"`
	Size            int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	ChunkSize       int64                  `protobuf:"varint,3,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	Etag            string                 `protobuf:"bytes,4,opt,name=etag,proto3" json:"etag,omitempty"`
	Chunks          []*ChunkRef            `protobuf:"bytes,5,rep,name=chunks,proto3" json:"chunks,omitempty"`
	PartChunkCounts []int64                `protobuf:"varint,6,rep,packed,name=part_chunk_counts,json=partChunkCounts,proto3" json:"part_chunk_counts,omitempty"`
	PartChecksums   []*PartChecksum        `protobuf:"bytes,7,rep,name=part_checksums,json=partChecksums,proto3" json:"part_checksums,omitempty"`
	BackendRef      *BackendRef            `protobuf:"bytes,8,opt,name=backend_ref,json=backendRef,proto3" json:"backend_ref,omitempty"`
	Sse             *SSEInfo               `protobuf:"bytes,12,opt,name=sse,proto3" json:"sse,omitempty"`
	PartChunks      []*PartRange           `protobuf:"bytes,13,rep,name=part_chunks,json=partChunks,proto3" json:"part_chunks,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_manifest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_manifest_proto_rawDescGZIP(), []int{0}
}

func (x *Manifest) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *Manifest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Manifest) GetChunkSize() int64 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *Manifest) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *Manifest) GetChunks() []*ChunkRef {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *Manifest) GetPartChunkCounts() []int64 {
	if x != nil {
		return x.PartChunkCounts
	}
	return nil
}

func (x *Manifest) GetPartChecksums() []*PartChecksum {
	if x != nil {
		return x.PartChecksums
	}
	return nil
}

func (x *Manifest) GetBackendRef() *BackendRef {
	if x != nil {
		return x.BackendRef
	}
	return nil
}

func (x *Manifest) GetSse() *SSEInfo {
	if x != nil {
		return x.Sse
	}
	return nil
}

func (x *Manifest) GetPartChunks() []*PartRange {
	if x != nil {
		return x.PartChunks
	}
	return nil
}

type PartRange struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PartNumber        int32                  `protobuf:"varint,1,opt,name=part_number,json=partNumber,proto3" json:"part_number,omitempty"`
	Offset            int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Size              int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Etag              string                 `protobuf:"bytes,4,opt,name=etag,proto3" json:"etag,omitempty"`
	ChecksumValue     string                 `protobuf:"bytes,5,opt,name=checksum_value,json=checksumValue,proto3" json:"checksum_value,omitempty"`
	ChecksumAlgorithm string                 `protobuf:"bytes,6,opt,name=checksum_algorithm,json=checksumAlgorithm,proto3" json:"checksum_algorithm,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PartRange) Reset() {
	*x = PartRange{}
	mi := &file_manifest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartRange) ProtoMessage() {}

func (x *PartRange) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartRange.ProtoReflect.Descriptor instead.
func (*PartRange) Descriptor() ([]byte, []int) {
	return file_manifest_proto_rawDescGZIP(), []int{1}
}

func (x *PartRange) GetPartNumber() int32 {
	if x != nil {
		return x.PartNumber
	}
	return 0
}

func (x *PartRange) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *PartRange) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PartRange) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *PartRange) GetChecksumValue() string {
	if x != nil {
		return x.ChecksumValue
	}
	return ""
}

func (x *PartRange) GetChecksumAlgorithm() string {
	if x != nil {
		return x.ChecksumAlgorithm
	}
	return ""
}

type ChunkRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       string                 `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Pool          string                 `protobuf:"bytes,2,opt,name=pool,proto3" json:"pool,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Oid           string                 `protobuf:"bytes,4,opt,name=oid,proto3" json:"oid,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkRef) Reset() {
	*x = ChunkRef{}
	mi := &file_manifest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkRef) ProtoMessage() {}

func (x *ChunkRef) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkRef.ProtoReflect.Descriptor instead.
func (*ChunkRef) Descriptor() ([]byte, []int) {
	return file_manifest_proto_rawDescGZIP(), []int{2}
}

func (x *ChunkRef) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *ChunkRef) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

func (x *ChunkRef) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ChunkRef) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

func (x *ChunkRef) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type PartChecksum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]string      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartChecksum) Reset() {
	*x = PartChecksum{}
	mi := &file_manifest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartChecksum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartChecksum) ProtoMessage() {}

func (x *PartChecksum) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartChecksum.ProtoReflect.Descriptor instead.
func (*PartChecksum) Descriptor() ([]byte, []int) {
	return file_manifest_proto_rawDescGZIP(), []int{3}
}

func (x *PartChecksum) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

type BackendRef struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Backend   string                 `protobuf:"bytes,1,opt,name=backend,proto3" json:"backend,omitempty"`
	Key       string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Etag      string                 `protobuf:"bytes,3,opt,name=etag,proto3" json:"etag,omitempty"`
	Size      int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	VersionId string                 `protobuf:"bytes,5,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	// cluster is the operator-labelled S3 cluster id that hosts this
	// backend object. Populated by s3.Backend.PutChunks (US-005 placement-
	// rebalance) so the rebalance worker can scan BackendRef-shape
	// manifests and decide whether a move is needed. Pre-US-005 rows have
	// an empty value; the worker skips them (rewriter cycle can backfill).
	Cluster       string `protobuf:"bytes,6,opt,name=cluster,proto3" json:"cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendRef) Reset() {
	*x = BackendRef{}
	mi := &file_manifest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendRef) ProtoMessage() {}

func (x *BackendRef) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendRef.ProtoReflect.Descriptor instead.
func (*BackendRef) Descriptor() ([]byte, []int) {
	return file_manifest_proto_rawDescGZIP(), []int{4}
}

func (x *BackendRef) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *BackendRef) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *BackendRef) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *BackendRef) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *BackendRef) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *BackendRef) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

type SSEInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Algorithm     string                 `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	KmsKeyId      string                 `protobuf:"bytes,3,opt,name=kms_key_id,json=kmsKeyId,proto3" json:"kms_key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSEInfo) Reset() {
	*x = SSEInfo{}
	mi := &file_manifest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSEInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSEInfo) ProtoMessage() {}

func (x *SSEInfo) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSEInfo.ProtoReflect.Descriptor instead.
func (*SSEInfo) Descriptor() ([]byte, []int) {
	return file_manifest_proto_rawDescGZIP(), []int{5}
}

func (x *SSEInfo) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *SSEInfo) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *SSEInfo) GetKmsKeyId() string {
	if x != nil {
		return x.KmsKeyId
	}
	return ""
}

var File_manifest_proto protoreflect.FileDescriptor

const file_manifest_proto_rawDesc = "" +
	"\n" +
	"\x0emanifest.proto\x12\x0estrata.data.v1\"\xb4\x03\n" +
	"\bManifest\x12\x14\n" +
	"\x05class\x18\x01 \x01(\tR\x05class\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x03 \x01(\x03R\tchunkSize\x12\x12\n" +
	"\x04etag\x18\x04 \x01(\tR\x04etag\x120\n" +
	"\x06chunks\x18\x05 \x03(\v2\x18.strata.data.v1.ChunkRefR\x06chunks\x12*\n" +
	"\x11part_chunk_counts\x18\x06 \x03(\x03R\x0fpartChunkCounts\x12C\n" +
	"\x0epart_checksums\x18\a \x03(\v2\x1c.strata.data.v1.PartChecksumR\rpartChecksums\x12;\n" +
	"\vbackend_ref\x18\b \x01(\v2\x1a.strata.data.v1.BackendRefR\n" +
	"backendRef\x12)\n" +
	"\x03sse\x18\f \x01(\v2\x17.strata.data.v1.SSEInfoR\x03sse\x12:\n" +
	"\vpart_chunks\x18\r \x03(\v2\x19.strata.data.v1.PartRangeR\n" +
	"partChunksJ\x04\b\t\x10\f\"\xc2\x01\n" +
	"\tPartRange\x12\x1f\n" +
	"\vpart_number\x18\x01 \x01(\x05R\n" +
	"partNumber\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x12\n" +
	"\x04etag\x18\x04 \x01(\tR\x04etag\x12%\n" +
	"\x0echecksum_value\x18\x05 \x01(\tR\rchecksumValue\x12-\n" +
	"\x12checksum_algorithm\x18\x06 \x01(\tR\x11checksumAlgorithm\"|\n" +
	"\bChunkRef\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x12\n" +
	"\x04pool\x18\x02 \x01(\tR\x04pool\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03oid\x18\x04 \x01(\tR\x03oid\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\"\x8b\x01\n" +
	"\fPartChecksum\x12@\n" +
	"\x06values\x18\x01 \x03(\v2(.strata.data.v1.PartChecksum.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x99\x01\n" +
	"\n" +
	"BackendRef\x12\x18\n" +
	"\abackend\x18\x01 \x01(\tR\abackend\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04etag\x18\x03 \x01(\tR\x04etag\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x1d\n" +
	"\n" +
	"version_id\x18\x05 \x01(\tR\tversionId\x12\x18\n" +
	"\acluster\x18\x06 \x01(\tR\acluster\"Y\n" +
	"\aSSEInfo\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm\x12\x1c\n" +
	"\n" +
	"kms_key_id\x18\x03 \x01(\tR\bkmsKeyIdBAZ?github.com/danchupin/strata/internal/data/manifestpb;manifestpbb\x06proto3"

var (
	file_manifest_proto_rawDescOnce sync.Once
	file_manifest_proto_rawDescData []byte
)

func file_manifest_proto_rawDescGZIP() []byte {
	file_manifest_proto_rawDescOnce.Do(func() {
		file_manifest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manifest_proto_rawDesc), len(file_manifest_proto_rawDesc)))
	})
	return file_manifest_proto_rawDescData
}

var file_manifest_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_manifest_proto_goTypes = []any{
	(*Manifest)(nil),     // 0: strata.data.v1.Manifest
	(*PartRange)(nil),    // 1: strata.data.v1.PartRange
	(*ChunkRef)(nil),     // 2: strata.data.v1.ChunkRef
	(*PartChecksum)(nil), // 3: strata.data.v1.PartChecksum
	(*BackendRef)(nil),   // 4: strata.data.v1.BackendRef
	(*SSEInfo)(nil),      // 5: strata.data.v1.SSEInfo
	nil,                  // 6: strata.data.v1.PartChecksum.ValuesEntry
}
var file_manifest_proto_depIdxs = []int32{
	2, // 0: strata.data.v1.Manifest.chunks:type_name -> strata.data.v1.ChunkRef
	3, // 1: strata.data.v1.Manifest.part_checksums:type_name -> strata.data.v1.PartChecksum
	4, // 2: strata.data.v1.Manifest.backend_ref:type_name -> strata.data.v1.BackendRef
	5, // 3: strata.data.v1.Manifest.sse:type_name -> strata.data.v1.SSEInfo
	1, // 4: strata.data.v1.Manifest.part_chunks:type_name -> strata.data.v1.PartRange
	6, // 5: strata.data.v1.PartChecksum.values:type_name -> strata.data.v1.PartChecksum.ValuesEntry
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_manifest_proto_init() }
func file_manifest_proto_init() {
	if File_manifest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manifest_proto_rawDesc), len(file_manifest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_manifest_proto_goTypes,
		DependencyIndexes: file_manifest_proto_depIdxs,
		MessageInfos:      file_manifest_proto_msgTypes,
	}.Build()
	File_manifest_proto = out.File
	file_manifest_proto_goTypes = nil
	file_manifest_proto_depIdxs = nil
}
