// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: internal/data/manifest.proto

package manifestpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Manifest mirrors data.Manifest (internal/data/manifest.go). New fields must
// keep wire compatibility — append-only field numbers, no renumbering.
type Manifest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Class     string                 `protobuf:"bytes,1,opt,name=class,proto3" json:"class,omitempty"`
	Size      int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	ChunkSize int64                  `protobuf:"varint,3,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	Etag      string                 `protobuf:"bytes,4,opt,name=etag,proto3" json:"etag,omitempty"`
	Chunks    []*ChunkRef            `protobuf:"bytes,5,rep,name=chunks,proto3" json:"chunks,omitempty"`
	// part_chunks records the number of chunks contributed by each part of a
	// multipart upload, in part order.
	PartChunks []int64 `protobuf:"varint,6,rep,packed,name=part_chunks,json=partChunks,proto3" json:"part_chunks,omitempty"`
	// part_checksums is the per-part stored checksum map (algo -> value), one
	// entry per part in PartNumber order.
	PartChecksums []*PartChecksum `protobuf:"bytes,7,rep,name=part_checksums,json=partChecksums,proto3" json:"part_checksums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_internal_data_manifest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_manifest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_internal_data_manifest_proto_rawDescGZIP(), []int{0}
}

func (x *Manifest) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *Manifest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Manifest) GetChunkSize() int64 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *Manifest) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *Manifest) GetChunks() []*ChunkRef {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *Manifest) GetPartChunks() []int64 {
	if x != nil {
		return x.PartChunks
	}
	return nil
}

func (x *Manifest) GetPartChecksums() []*PartChecksum {
	if x != nil {
		return x.PartChecksums
	}
	return nil
}

type ChunkRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       string                 `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Pool          string                 `protobuf:"bytes,2,opt,name=pool,proto3" json:"pool,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Oid           string                 `protobuf:"bytes,4,opt,name=oid,proto3" json:"oid,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkRef) Reset() {
	*x = ChunkRef{}
	mi := &file_internal_data_manifest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkRef) ProtoMessage() {}

func (x *ChunkRef) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_manifest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkRef.ProtoReflect.Descriptor instead.
func (*ChunkRef) Descriptor() ([]byte, []int) {
	return file_internal_data_manifest_proto_rawDescGZIP(), []int{1}
}

func (x *ChunkRef) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *ChunkRef) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

func (x *ChunkRef) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ChunkRef) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

func (x *ChunkRef) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type PartChecksum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]string      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartChecksum) Reset() {
	*x = PartChecksum{}
	mi := &file_internal_data_manifest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartChecksum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartChecksum) ProtoMessage() {}

func (x *PartChecksum) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_manifest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartChecksum.ProtoReflect.Descriptor instead.
func (*PartChecksum) Descriptor() ([]byte, []int) {
	return file_internal_data_manifest_proto_rawDescGZIP(), []int{2}
}

func (x *PartChecksum) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_internal_data_manifest_proto protoreflect.FileDescriptor

const file_internal_data_manifest_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/data/manifest.proto\x12\x0estrata.data.v1\"\xff\x01\n" +
	"\bManifest\x12\x14\n" +
	"\x05class\x18\x01 \x01(\tR\x05class\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x03 \x01(\x03R\tchunkSize\x12\x12\n" +
	"\x04etag\x18\x04 \x01(\tR\x04etag\x120\n" +
	"\x06chunks\x18\x05 \x03(\v2\x18.strata.data.v1.ChunkRefR\x06chunks\x12\x1f\n" +
	"\vpart_chunks\x18\x06 \x03(\x03R\n" +
	"partChunks\x12C\n" +
	"\x0epart_checksums\x18\a \x03(\v2\x1c.strata.data.v1.PartChecksumR\rpartChecksums\"|\n" +
	"\bChunkRef\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x12\n" +
	"\x04pool\x18\x02 \x01(\tR\x04pool\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03oid\x18\x04 \x01(\tR\x03oid\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\"\x8b\x01\n" +
	"\fPartChecksum\x12@\n" +
	"\x06values\x18\x01 \x03(\v2(.strata.data.v1.PartChecksum.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01BAZ?github.com/danchupin/strata/internal/data/manifestpb;manifestpbb\x06proto3"

var (
	file_internal_data_manifest_proto_rawDescOnce sync.Once
	file_internal_data_manifest_proto_rawDescData []byte
)

func file_internal_data_manifest_proto_rawDescGZIP() []byte {
	file_internal_data_manifest_proto_rawDescOnce.Do(func() {
		file_internal_data_manifest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_data_manifest_proto_rawDesc), len(file_internal_data_manifest_proto_rawDesc)))
	})
	return file_internal_data_manifest_proto_rawDescData
}

var file_internal_data_manifest_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_data_manifest_proto_goTypes = []any{
	(*Manifest)(nil),     // 0: strata.data.v1.Manifest
	(*ChunkRef)(nil),     // 1: strata.data.v1.ChunkRef
	(*PartChecksum)(nil), // 2: strata.data.v1.PartChecksum
	nil,                  // 3: strata.data.v1.PartChecksum.ValuesEntry
}
var file_internal_data_manifest_proto_depIdxs = []int32{
	1, // 0: strata.data.v1.Manifest.chunks:type_name -> strata.data.v1.ChunkRef
	2, // 1: strata.data.v1.Manifest.part_checksums:type_name -> strata.data.v1.PartChecksum
	3, // 2: strata.data.v1.PartChecksum.values:type_name -> strata.data.v1.PartChecksum.ValuesEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_data_manifest_proto_init() }
func file_internal_data_manifest_proto_init() {
	if File_internal_data_manifest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_data_manifest_proto_rawDesc), len(file_internal_data_manifest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_data_manifest_proto_goTypes,
		DependencyIndexes: file_internal_data_manifest_proto_depIdxs,
		MessageInfos:      file_internal_data_manifest_proto_msgTypes,
	}.Build()
	File_internal_data_manifest_proto = out.File
	file_internal_data_manifest_proto_goTypes = nil
	file_internal_data_manifest_proto_depIdxs = nil
}
