#!/usr/bin/env bash
# scripts/qa/coverage.sh — per-package coverage baseline for the QA
# production-readiness cycle (US-001).
#
# Runs `go test -cover ./...` on the DEFAULT build tag (TiKV + memory, no
# ceph/librados) and emits a per-package coverage table to
# tasks/qa-readiness-report.md, replacing the block between the
# COVERAGE-TABLE-START / COVERAGE-TABLE-END markers.
#
# CGO note (FR-4): on a macOS box without the Xcode license accepted, the
# cgo runtime (and the darwin-only `gosigar` sysctl path pulled transitively by
# the process-metrics collector) fail to build for a handful of packages
# (cmd/strata, cmd/strata/admin, internal/meta/tikv, internal/metrics,
# internal/serverapp). That is an ENV issue, not a code bug. This script makes
# two passes — default CGO, then CGO_ENABLED=0 — and keeps the real number from
# whichever pass built each package. Packages that fail BOTH passes are recorded
# as "CI" (the Linux CI run is the source of truth). On a Linux CI runner with a
# C toolchain present, the first pass measures every package and there are no
# gaps.
#
# Usage: scripts/qa/coverage.sh          # update the report in place
#        CHECK=1 scripts/qa/coverage.sh  # print table to stdout, do not write
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

REPORT="tasks/qa-readiness-report.md"
RUN1="$(mktemp)"
RUN0="$(mktemp)"
trap 'rm -f "$RUN1" "$RUN0"' EXIT

echo "[coverage] pass 1: go test -cover ./... (default CGO)" >&2
go test -cover ./... >"$RUN1" 2>&1 || true

echo "[coverage] pass 2: CGO_ENABLED=0 go test -cover ./... (recover darwin cgo-blocked pkgs)" >&2
CGO_ENABLED=0 go test -cover ./... >"$RUN0" 2>&1 || true

# Merge the two passes and render the markdown table.
TABLE="$(python3 - "$RUN1" "$RUN0" <<'PY'
import re, sys

def parse(fn):
    cov = {}
    for line in open(fn):
        m = re.match(r'(?:ok|FAIL|\?)?\s*(github\.com/danchupin/strata\S*)\s+.*coverage:\s+([\d.]+)%', line)
        if m:
            cov[m.group(1)] = float(m.group(2)); continue
        m = re.match(r'\?\s+(github\.com/danchupin/strata\S*)\s+\[no test files\]', line)
        if m and m.group(1) not in cov:
            cov[m.group(1)] = 'notest'; continue
        m = re.match(r'FAIL\s+(github\.com/danchupin/strata\S*)\s+\[build failed\]', line)
        if m:
            cov.setdefault(m.group(1), 'BUILD')
    return cov

c1, c0 = parse(sys.argv[1]), parse(sys.argv[2])
allp = sorted(set(c1) | set(c0))

def best(p):
    for c in (c1, c0):
        if isinstance(c.get(p), float):
            return c[p]
    for c in (c1, c0):
        if c.get(p) == 'notest':
            return 'notest'
    return 'BUILD'

print("| Package | Coverage |")
print("|---------|----------|")
for p in allp:
    short = p.replace('github.com/danchupin/strata', '').lstrip('/') or '(root)'
    b = best(p)
    if isinstance(b, float):
        v = f"{b:.1f}%"
    elif b == 'notest':
        v = "— (no test files)"
    else:
        v = "CI (local env-blocked)"
    print(f"| `{short}` | {v} |")
PY
)"

if [[ "${CHECK:-}" == "1" ]]; then
    echo "$TABLE"
    exit 0
fi

# Splice the table between the markers in the report.
python3 - "$REPORT" <<PY
import re, sys
path = sys.argv[1]
table = '''$TABLE'''
src = open(path).read()
start, end = "<!-- COVERAGE-TABLE-START -->", "<!-- COVERAGE-TABLE-END -->"
block = start + "\n_Generated by \`scripts/qa/coverage.sh\` — do not hand-edit._\n\n" + table + "\n" + end
src = re.sub(re.escape(start) + r".*?" + re.escape(end), lambda m: block, src, flags=re.S)
open(path, "w").write(src)
print("[coverage] wrote table into " + path)
PY
